version: '3.8'

services:
  web:
    image: ${ECR_REPOSITORY}
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
