version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/docker:${IMAGE_TAG}
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - ${{ secrets.ENV_FILE }}

    volumes:
      - .:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

  db:
    image: postgres:13
    env_file:
      - ${{ secrets.ENV_FILE }}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
